services:
  web:
    image: "node:18"
    container_name: nextjs-app
    working_dir: /app
    volumes:
      - ".:/app"
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - "NEXT_PUBLIC_API=http://localhost:3005"
    command: sh -c "npm install && npm run dev"
networks:
  default:
    name: bill-tracker-network
  api:
    external: true
