services:
  web:
    image: "node:18"
    container_name: bill-tracker
    working_dir: /app
    volumes:
      - ".:/app"
      - /app/node_modules
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - "NEXT_PUBLIC_API=http://srv596601.hstgr.cloud:3005"
    command: sh -c "npm run vps-deploy"
networks:
  default:
    name: bill-tracker-network
  api:
    external: true
