export const currencies: Models.Currency[] = [
  { name: "Afghan Afghani", symbol: "AFN", iso: "AFN", currencySymbol: "؋" },
  { name: "Albanian Lek", symbol: "ALL", iso: "ALL", currencySymbol: "L" },
  { name: "Algerian Dinar", symbol: "DZD", iso: "DZD", currencySymbol: "د.ج" },
  { name: "Andorran Euro", symbol: "EUR", iso: "EUR", currencySymbol: "€" },
  { name: "Angolan Kwanza", symbol: "AOA", iso: "AOA", currencySymbol: "Kz" },
  {
    name: "East Caribbean Dollar",
    symbol: "XCD",
    iso: "XCD",
    currencySymbol: "$",
  },
  { name: "Argentine Peso", symbol: "ARS", iso: "ARS", currencySymbol: "$" },
  { name: "Armenian Dram", symbol: "AMD", iso: "AMD", currencySymbol: "֏" },
  { name: "Aruban Florin", symbol: "AWG", iso: "AWG", currencySymbol: "ƒ" },
  { name: "Australian Dollar", symbol: "AUD", iso: "AUD", currencySymbol: "$" },
  { name: "Azerbaijani Manat", symbol: "AZN", iso: "AZN", currencySymbol: "₼" },
  { name: "Bahamian Dollar", symbol: "BSD", iso: "BSD", currencySymbol: "$" },
  { name: "Bahraini Dinar", symbol: "BHD", iso: "BHD", currencySymbol: ".د.ب" },
  { name: "Bangladeshi Taka", symbol: "BDT", iso: "BDT", currencySymbol: "৳" },
  { name: "Barbados Dollar", symbol: "BBD", iso: "BBD", currencySymbol: "$" },
  { name: "Belarusian Ruble", symbol: "BYN", iso: "BYN", currencySymbol: "Br" },
  {
    name: "Belgian Franc (pre-Euro)",
    symbol: "BEF",
    iso: "BEF",
    currencySymbol: "₣",
  },
  { name: "Belize Dollar", symbol: "BZD", iso: "BZD", currencySymbol: "$" },
  { name: "Bermudian Dollar", symbol: "BMD", iso: "BMD", currencySymbol: "$" },
  {
    name: "Bhutanese Ngultrum",
    symbol: "BTN",
    iso: "BTN",
    currencySymbol: "Nu.",
  },
  {
    name: "Bolivian Boliviano",
    symbol: "BOB",
    iso: "BOB",
    currencySymbol: "Bs.",
  },
  {
    name: "Bosnian Convertible Mark",
    symbol: "BAM",
    iso: "BAM",
    currencySymbol: "KM",
  },
  { name: "Brazilian Real", symbol: "BRL", iso: "BRL", currencySymbol: "R$" },
  {
    name: "British Pound Sterling",
    symbol: "GBP",
    iso: "GBP",
    currencySymbol: "£",
  },
  { name: "Brunei Dollar", symbol: "BND", iso: "BND", currencySymbol: "$" },
  { name: "Bulgarian Lev", symbol: "BGN", iso: "BGN", currencySymbol: "лв" },
  { name: "Burundian Franc", symbol: "BIF", iso: "BIF", currencySymbol: "FBu" },
  { name: "Cambodian Riel", symbol: "KHR", iso: "KHR", currencySymbol: "៛" },
  { name: "Canadian Dollar", symbol: "CAD", iso: "CAD", currencySymbol: "$" },
  {
    name: "Cape Verdean Escudo",
    symbol: "CVE",
    iso: "CVE",
    currencySymbol: "$",
  },
  {
    name: "Cayman Islands Dollar",
    symbol: "KYD",
    iso: "KYD",
    currencySymbol: "$",
  },
  {
    name: "Central African CFA Franc",
    symbol: "XAF",
    iso: "XAF",
    currencySymbol: "FCFA",
  },
  { name: "Chilean Peso", symbol: "CLP", iso: "CLP", currencySymbol: "$" },
  { name: "Chinese Yuan", symbol: "CNY", iso: "CNY", currencySymbol: "¥" },
  { name: "Colombian Peso", symbol: "COP", iso: "COP", currencySymbol: "$" },
  { name: "Comorian Franc", symbol: "KMF", iso: "KMF", currencySymbol: "CF" },
  {
    name: "Congolese Franc (Congo-Brazzaville)",
    symbol: "XAF",
    iso: "XAF",
    currencySymbol: "FCFA",
  },
  {
    name: "Congolese Franc (Congo-Kinshasa)",
    symbol: "CDF",
    iso: "CDF",
    currencySymbol: "FC",
  },
  { name: "Costa Rican Colón", symbol: "CRC", iso: "CRC", currencySymbol: "₡" },
  { name: "Croatian Kuna", symbol: "HRK", iso: "HRK", currencySymbol: "kn" },
  { name: "Cuban Peso", symbol: "CUP", iso: "CUP", currencySymbol: "$" },
  { name: "Czech Koruna", symbol: "CZK", iso: "CZK", currencySymbol: "Kč" },
  { name: "Danish Krone", symbol: "DKK", iso: "DKK", currencySymbol: "kr" },
  {
    name: "Djiboutian Franc",
    symbol: "DJF",
    iso: "DJF",
    currencySymbol: "Fdj",
  },
  { name: "Dominican Peso", symbol: "DOP", iso: "DOP", currencySymbol: "$" },
  {
    name: "Dutch Guilder (pre-Euro)",
    symbol: "NLG",
    iso: "NLG",
    currencySymbol: "fl",
  },
  {
    name: "East Caribbean Dollar",
    symbol: "XCD",
    iso: "XCD",
    currencySymbol: "$",
  },
  { name: "Egyptian Pound", symbol: "EGP", iso: "EGP", currencySymbol: "ج.م" },
  { name: "Salvadoran Colón", symbol: "SVC", iso: "SVC", currencySymbol: "$" },
  {
    name: "Equatorial Guinean Franc",
    symbol: "XAF",
    iso: "XAF",
    currencySymbol: "FCFA",
  },
  { name: "Eritrean Nakfa", symbol: "ERN", iso: "ERN", currencySymbol: "Nkf" },
  {
    name: "Estonian Kroon (pre-Euro)",
    symbol: "EEK",
    iso: "EEK",
    currencySymbol: "kr",
  },
  { name: "Ethiopian Birr", symbol: "ETB", iso: "ETB", currencySymbol: "Br" },
  { name: "Euro", symbol: "EUR", iso: "EUR", currencySymbol: "€" },
  { name: "Fijian Dollar", symbol: "FJD", iso: "FJD", currencySymbol: "$" },
  { name: "Filipino Peso", symbol: "PHP", iso: "PHP", currencySymbol: "₱" },
  {
    name: "Finnish Markka (pre-Euro)",
    symbol: "FIM",
    iso: "FIM",
    currencySymbol: "mk",
  },
  {
    name: "French Franc (pre-Euro)",
    symbol: "FRF",
    iso: "FRF",
    currencySymbol: "₣",
  },
  { name: "Gambian Dalasi", symbol: "GMD", iso: "GMD", currencySymbol: "D" },
  { name: "Georgian Lari", symbol: "GEL", iso: "GEL", currencySymbol: "₾" },
  {
    name: "German Mark (pre-Euro)",
    symbol: "DEM",
    iso: "DEM",
    currencySymbol: "DM",
  },
  { name: "Ghanaian Cedi", symbol: "GHS", iso: "GHS", currencySymbol: "₵" },
  { name: "Gibraltar Pound", symbol: "GIP", iso: "GIP", currencySymbol: "£" },
  {
    name: "Greek Drachma (pre-Euro)",
    symbol: "GRD",
    iso: "GRD",
    currencySymbol: "₯",
  },
  {
    name: "Guatemalan Quetzal",
    symbol: "GTQ",
    iso: "GTQ",
    currencySymbol: "Q",
  },
  { name: "Guinean Franc", symbol: "GNF", iso: "GNF", currencySymbol: "FG" },
  { name: "Guyanese Dollar", symbol: "GYD", iso: "GYD", currencySymbol: "$" },
  { name: "Haitian Gourde", symbol: "HTG", iso: "HTG", currencySymbol: "G" },
  { name: "Honduran Lempira", symbol: "HNL", iso: "HNL", currencySymbol: "L" },
  { name: "Hong Kong Dollar", symbol: "HKD", iso: "HKD", currencySymbol: "$" },
  { name: "Hungarian Forint", symbol: "HUF", iso: "HUF", currencySymbol: "Ft" },
  { name: "Icelandic Króna", symbol: "ISK", iso: "ISK", currencySymbol: "kr" },
  { name: "Indian Rupee", symbol: "INR", iso: "INR", currencySymbol: "₹" },
  {
    name: "Indonesian Rupiah",
    symbol: "IDR",
    iso: "IDR",
    currencySymbol: "Rp",
  },
  { name: "Iranian Rial", symbol: "IRR", iso: "IRR", currencySymbol: "﷼" },
  { name: "Iraqi Dinar", symbol: "IQD", iso: "IQD", currencySymbol: "ع.د" },
  {
    name: "Israeli New Sheqel",
    symbol: "ILS",
    iso: "ILS",
    currencySymbol: "₪",
  },
  {
    name: "Italian Lira (pre-Euro)",
    symbol: "ITL",
    iso: "ITL",
    currencySymbol: "₤",
  },
  { name: "Jamaican Dollar", symbol: "JMD", iso: "JMD", currencySymbol: "$" },
  { name: "Japanese Yen", symbol: "JPY", iso: "JPY", currencySymbol: "¥" },
  { name: "Jordanian Dinar", symbol: "JOD", iso: "JOD", currencySymbol: "د.أ" },
  { name: "Kazakhstani Tenge", symbol: "KZT", iso: "KZT", currencySymbol: "₸" },
  { name: "Kenyan Shilling", symbol: "KES", iso: "KES", currencySymbol: "KSh" },
  { name: "Kuwaiti Dinar", symbol: "KWD", iso: "KWD", currencySymbol: "د.ك" },
  { name: "Kyrgyzstani Som", symbol: "KGS", iso: "KGS", currencySymbol: "с" },
  { name: "Laotian Kip", symbol: "LAK", iso: "LAK", currencySymbol: "₭" },
  {
    name: "Latvian Lats (pre-Euro)",
    symbol: "LVL",
    iso: "LVL",
    currencySymbol: "Ls",
  },
  { name: "Lebanese Pound", symbol: "LBP", iso: "LBP", currencySymbol: "ل.ل" },
  { name: "Lesotho Loti", symbol: "LSL", iso: "LSL", currencySymbol: "M" },
  { name: "Liberian Dollar", symbol: "LRD", iso: "LRD", currencySymbol: "$" },
  { name: "Libyan Dinar", symbol: "LYD", iso: "LYD", currencySymbol: "د.ل" },
  {
    name: "Lithuanian Litas (pre-Euro)",
    symbol: "LTL",
    iso: "LTL",
    currencySymbol: "Lt",
  },
  {
    name: "Macanese Pataca",
    symbol: "MOP",
    iso: "MOP",
    currencySymbol: "MOP$",
  },
  {
    name: "Macedonian Denar",
    symbol: "MKD",
    iso: "MKD",
    currencySymbol: "ден",
  },
  { name: "Malagasy Ariary", symbol: "MGA", iso: "MGA", currencySymbol: "Ar" },
  { name: "Malawian Kwacha", symbol: "MWK", iso: "MWK", currencySymbol: "MK" },
  {
    name: "Malaysian Ringgit",
    symbol: "MYR",
    iso: "MYR",
    currencySymbol: "RM",
  },
  {
    name: "Maldivian Rufiyaa",
    symbol: "MVR",
    iso: "MVR",
    currencySymbol: "Rf",
  },
  { name: "Mauritian Rupee", symbol: "MUR", iso: "MUR", currencySymbol: "₨" },
  { name: "Mexican Peso", symbol: "MXN", iso: "MXN", currencySymbol: "$" },
  { name: "Moldovan Leu", symbol: "MDL", iso: "MDL", currencySymbol: "L" },
  {
    name: "Moroccan Dirham",
    symbol: "MAD",
    iso: "MAD",
    currencySymbol: "د.م.",
  },
  {
    name: "Mozambican Metical",
    symbol: "MZN",
    iso: "MZN",
    currencySymbol: "MT",
  },
  { name: "Myanmar Kyat", symbol: "MMK", iso: "MMK", currencySymbol: "K" },
  { name: "Namibian Dollar", symbol: "NAD", iso: "NAD", currencySymbol: "$" },
  { name: "Nepalese Rupee", symbol: "NPR", iso: "NPR", currencySymbol: "₨" },
  {
    name: "Netherlands Antillean Guilder",
    symbol: "ANG",
    iso: "ANG",
    currencySymbol: "ƒ",
  },
  {
    name: "New Zealand Dollar",
    symbol: "NZD",
    iso: "NZD",
    currencySymbol: "$",
  },
  {
    name: "Nicaraguan Córdoba",
    symbol: "NIO",
    iso: "NIO",
    currencySymbol: "C$",
  },
  { name: "Nigerian Naira", symbol: "NGN", iso: "NGN", currencySymbol: "₦" },
  { name: "North Korean Won", symbol: "KPW", iso: "KPW", currencySymbol: "₩" },
  { name: "Norwegian Krone", symbol: "NOK", iso: "NOK", currencySymbol: "kr" },
  { name: "Omani Rial", symbol: "OMR", iso: "OMR", currencySymbol: "ر.ع." },
  { name: "Pakistani Rupee", symbol: "PKR", iso: "PKR", currencySymbol: "₨" },
  {
    name: "Panamanian Balboa",
    symbol: "PAB",
    iso: "PAB",
    currencySymbol: "B/.",
  },
  {
    name: "Papua New Guinean Kina",
    symbol: "PGK",
    iso: "PGK",
    currencySymbol: "K",
  },
  {
    name: "Paraguayan Guaraní",
    symbol: "PYG",
    iso: "PYG",
    currencySymbol: "₲",
  },
  { name: "Peruvian Sol", symbol: "PEN", iso: "PEN", currencySymbol: "S/" },
  { name: "Philippine Peso", symbol: "PHP", iso: "PHP", currencySymbol: "₱" },
  { name: "Polish Zloty", symbol: "PLN", iso: "PLN", currencySymbol: "zł" },
  {
    name: "Portuguese Escudo (pre-Euro)",
    symbol: "PTE",
    iso: "PTE",
    currencySymbol: "Esc",
  },
  { name: "Qatari Rial", symbol: "QAR", iso: "QAR", currencySymbol: "ر.ق" },
  { name: "Romanian Leu", symbol: "RON", iso: "RON", currencySymbol: "lei" },
  { name: "Russian Ruble", symbol: "RUB", iso: "RUB", currencySymbol: "₽" },
  { name: "Rwandan Franc", symbol: "RWF", iso: "RWF", currencySymbol: "FRw" },
  { name: "Sao Tomean Dobra", symbol: "STN", iso: "STN", currencySymbol: "Db" },
  { name: "Saudi Riyal", symbol: "SAR", iso: "SAR", currencySymbol: "ر.س" },
  { name: "Serbian Dinar", symbol: "RSD", iso: "RSD", currencySymbol: "Дин." },
  { name: "Seychellois Rupee", symbol: "SCR", iso: "SCR", currencySymbol: "₨" },
  { name: "Singapore Dollar", symbol: "SGD", iso: "SGD", currencySymbol: "$" },
  { name: "Slovak Koruna", symbol: "SKK", iso: "SKK", currencySymbol: "Sk" },
  {
    name: "Slovenian Tolar (pre-Euro)",
    symbol: "SIT",
    iso: "SIT",
    currencySymbol: "T",
  },
  {
    name: "Solomon Islands Dollar",
    symbol: "AUD",
    iso: "AUD",
    currencySymbol: "$",
  },
  { name: "Somali Shilling", symbol: "SOS", iso: "SOS", currencySymbol: "S" },
  {
    name: "South African Rand",
    symbol: "ZAR",
    iso: "ZAR",
    currencySymbol: "R",
  },
  { name: "South Korean Won", symbol: "KRW", iso: "KRW", currencySymbol: "₩" },
  {
    name: "Spanish Peseta (pre-Euro)",
    symbol: "ESP",
    iso: "ESP",
    currencySymbol: "Pts",
  },
  { name: "Sri Lankan Rupee", symbol: "LKR", iso: "LKR", currencySymbol: "Rs" },
  { name: "Swedish Krona", symbol: "SEK", iso: "SEK", currencySymbol: "kr" },
  { name: "Swiss Franc", symbol: "CHF", iso: "CHF", currencySymbol: "CHF" },
  { name: "Syrian Pound", symbol: "SYP", iso: "SYP", currencySymbol: "ل.س" },
  { name: "Taiwan Dollar", symbol: "TWD", iso: "TWD", currencySymbol: "NT$" },
  {
    name: "Tajikistani Somoni",
    symbol: "TJS",
    iso: "TJS",
    currencySymbol: "ЅМ",
  },
  {
    name: "Tanzanian Shilling",
    symbol: "TZS",
    iso: "TZS",
    currencySymbol: "TSh",
  },
  { name: "Thai Baht", symbol: "THB", iso: "THB", currencySymbol: "฿" },
  { name: "Tunisian Dinar", symbol: "TND", iso: "TND", currencySymbol: "د.ت" },
  { name: "Turkish Lira", symbol: "TRY", iso: "TRY", currencySymbol: "₺" },
  {
    name: "Turkmenistani Manat",
    symbol: "TMT",
    iso: "TMT",
    currencySymbol: "m",
  },
  {
    name: "Ugandan Shilling",
    symbol: "UGX",
    iso: "UGX",
    currencySymbol: "USh",
  },
  { name: "Ukrainian Hryvnia", symbol: "UAH", iso: "UAH", currencySymbol: "₴" },
  {
    name: "United Arab Emirates Dirham",
    symbol: "AED",
    iso: "AED",
    currencySymbol: "د.إ",
  },
  {
    name: "United Kingdom Pound",
    symbol: "GBP",
    iso: "GBP",
    currencySymbol: "£",
  },
  {
    name: "United States Dollar",
    symbol: "USD",
    iso: "USD",
    currencySymbol: "$",
  },
  { name: "Uruguayan Peso", symbol: "UYU", iso: "UYU", currencySymbol: "$" },
  { name: "Uzbekistani Som", symbol: "UZS", iso: "UZS", currencySymbol: "с" },
  { name: "Vanuatu Vatu", symbol: "VUV", iso: "VUV", currencySymbol: "Vt" },
  {
    name: "Venezuelan Bolívar",
    symbol: "VES",
    iso: "VES",
    currencySymbol: "Bs.",
  },
  { name: "Vietnamese Dong", symbol: "VND", iso: "VND", currencySymbol: "₫" },
  { name: "Yemeni Rial", symbol: "YER", iso: "YER", currencySymbol: "﷼" },
  { name: "Zambian Kwacha", symbol: "ZMW", iso: "ZMW", currencySymbol: "K" },
  { name: "Zimbabwean Dollar", symbol: "ZWL", iso: "ZWL", currencySymbol: "$" },
];
