export const currencies = [
    { name: 'Afghan Afghani', symbol: 'AFN', iso: 'AFN' },
    { name: 'Albanian Lek', symbol: 'ALL', iso: 'ALL' },
    { name: 'Algerian Dinar', symbol: 'DZD', iso: 'DZD' },
    { name: 'Andorran Euro', symbol: 'EUR', iso: 'EUR' },
    { name: 'Angolan Kwanza', symbol: 'AOA', iso: 'AOA' },
    { name: 'East Caribbean Dollar', symbol: 'XCD', iso: 'XCD' },
    { name: 'Argentine Peso', symbol: 'ARS', iso: 'ARS' },
    { name: 'Armenian Dram', symbol: 'AMD', iso: 'AMD' },
    { name: 'Aruban Florin', symbol: 'AWG', iso: 'AWG' },
    { name: 'Australian Dollar', symbol: 'AUD', iso: 'AUD' },
    { name: 'Azerbaijani Manat', symbol: 'AZN', iso: 'AZN' },
    { name: 'Bahamian Dollar', symbol: 'BSD', iso: 'BSD' },
    { name: 'Bahraini Dinar', symbol: 'BHD', iso: 'BHD' },
    { name: 'Bangladeshi Taka', symbol: 'BDT', iso: 'BDT' },
    { name: 'Barbados Dollar', symbol: 'BBD', iso: 'BBD' },
    { name: 'Belarusian Ruble', symbol: 'BYN', iso: 'BYN' },
    { name: 'Belgian Franc (pre-Euro)', symbol: 'BEF', iso: 'BEF' },
    { name: 'Belize Dollar', symbol: 'BZD', iso: 'BZD' },
    { name: 'Bermudian Dollar', symbol: 'BMD', iso: 'BMD' },
    { name: 'Bhutanese Ngultrum', symbol: 'BTN', iso: 'BTN' },
    { name: 'Bolivian Boliviano', symbol: 'BOB', iso: 'BOB' },
    { name: 'Bosnian Convertible Mark', symbol: 'BAM', iso: 'BAM' },
    { name: 'Brazilian Real', symbol: 'BRL', iso: 'BRL' },
    { name: 'British Pound Sterling', symbol: 'GBP', iso: 'GBP' },
    { name: 'Brunei Dollar', symbol: 'BND', iso: 'BND' },
    { name: 'Bulgarian Lev', symbol: 'BGN', iso: 'BGN' },
    { name: 'Burundian Franc', symbol: 'BIF', iso: 'BIF' },
    { name: 'Cambodian Riel', symbol: 'KHR', iso: 'KHR' },
    { name: 'Canadian Dollar', symbol: 'CAD', iso: 'CAD' },
    { name: 'Cape Verdean Escudo', symbol: 'CVE', iso: 'CVE' },
    { name: 'Cayman Islands Dollar', symbol: 'KYD', iso: 'KYD' },
    { name: 'Central African CFA Franc', symbol: 'XAF', iso: 'XAF' },
    { name: 'Chilean Peso', symbol: 'CLP', iso: 'CLP' },
    { name: 'Chinese Yuan', symbol: 'CNY', iso: 'CNY' },
    { name: 'Colombian Peso', symbol: 'COP', iso: 'COP' },
    { name: 'Comorian Franc', symbol: 'KMF', iso: 'KMF' },
    { name: 'Congolese Franc (Congo-Brazzaville)', symbol: 'XAF', iso: 'XAF' },
    { name: 'Congolese Franc (Congo-Kinshasa)', symbol: 'CDF', iso: 'CDF' },
    { name: 'Costa Rican Colón', symbol: 'CRC', iso: 'CRC' },
    { name: 'Croatian Kuna', symbol: 'HRK', iso: 'HRK' },
    { name: 'Cuban Peso', symbol: 'CUP', iso: 'CUP' },
    { name: 'Czech Koruna', symbol: 'CZK', iso: 'CZK' },
    { name: 'Danish Krone', symbol: 'DKK', iso: 'DKK' },
    { name: 'Djiboutian Franc', symbol: 'DJF', iso: 'DJF' },
    { name: 'Dominican Peso', symbol: 'DOP', iso: 'DOP' },
    { name: 'Dutch Guilder (pre-Euro)', symbol: 'NLG', iso: 'NLG' },
    { name: 'East Caribbean Dollar', symbol: 'XCD', iso: 'XCD' },
    { name: 'Egyptian Pound', symbol: 'EGP', iso: 'EGP' },
    { name: 'Salvadoran Colón', symbol: 'SVC', iso: 'SVC' },
    { name: 'Equatorial Guinean Franc', symbol: 'XAF', iso: 'XAF' },
    { name: 'Eritrean Nakfa', symbol: 'ERN', iso: 'ERN' },
    { name: 'Estonian Kroon (pre-Euro)', symbol: 'EEK', iso: 'EEK' },
    { name: 'Ethiopian Birr', symbol: 'ETB', iso: 'ETB' },
    { name: 'Euro', symbol: 'EUR', iso: 'EUR' },
    { name: 'Fijian Dollar', symbol: 'FJD', iso: 'FJD' },
    { name: 'Filipino Peso', symbol: 'PHP', iso: 'PHP' },
    { name: 'Finnish Markka (pre-Euro)', symbol: 'FIM', iso: 'FIM' },
    { name: 'French Franc (pre-Euro)', symbol: 'FRF', iso: 'FRF' },
    { name: 'Gambian Dalasi', symbol: 'GMD', iso: 'GMD' },
    { name: 'Georgian Lari', symbol: 'GEL', iso: 'GEL' },
    { name: 'German Mark (pre-Euro)', symbol: 'DEM', iso: 'DEM' },
    { name: 'Ghanaian Cedi', symbol: 'GHS', iso: 'GHS' },
    { name: 'Gibraltar Pound', symbol: 'GIP', iso: 'GIP' },
    { name: 'Greek Drachma (pre-Euro)', symbol: 'GRD', iso: 'GRD' },
    { name: 'Guatemalan Quetzal', symbol: 'GTQ', iso: 'GTQ' },
    { name: 'Guinean Franc', symbol: 'GNF', iso: 'GNF' },
    { name: 'Guyanese Dollar', symbol: 'GYD', iso: 'GYD' },
    { name: 'Haitian Gourde', symbol: 'HTG', iso: 'HTG' },
    { name: 'Honduran Lempira', symbol: 'HNL', iso: 'HNL' },
    { name: 'Hungarian Forint', symbol: 'HUF', iso: 'HUF' },
    { name: 'Icelandic Króna', symbol: 'ISK', iso: 'ISK' },
    { name: 'Indian Rupee', symbol: 'INR', iso: 'INR' },
    { name: 'Indonesian Rupiah', symbol: 'IDR', iso: 'IDR' },
    { name: 'Iranian Rial', symbol: 'IRR', iso: 'IRR' },
    { name: 'Iraqi Dinar', symbol: 'IQD', iso: 'IQD' },
    { name: 'Israeli New Shekel', symbol: 'ILS', iso: 'ILS' },
    { name: 'Italian Lira (pre-Euro)', symbol: 'ITL', iso: 'ITL' },
    { name: 'Jamaican Dollar', symbol: 'JMD', iso: 'JMD' },
    { name: 'Japanese Yen', symbol: 'JPY', iso: 'JPY' },
    { name: 'Jordanian Dinar', symbol: 'JOD', iso: 'JOD' },
    { name: 'Kazakhstani Tenge', symbol: 'KZT', iso: 'KZT' },
    { name: 'Kenyan Shilling', symbol: 'KES', iso: 'KES' },
    { name: 'Kiribati Dollar', symbol: 'AUD', iso: 'AUD' },
    { name: 'Korean Won', symbol: 'KRW', iso: 'KRW' },
    { name: 'Kuwaiti Dinar', symbol: 'KWD', iso: 'KWD' },
    { name: 'Kyrgyzstani Som', symbol: 'KGS', iso: 'KGS' },
    { name: 'Laotian Kip', symbol: 'LAK', iso: 'LAK' },
    { name: 'Latvian Lats (pre-Euro)', symbol: 'LVL', iso: 'LVL' },
    { name: 'Lebanese Pound', symbol: 'LBP', iso: 'LBP' },
    { name: 'Lesotho Loti', symbol: 'LSL', iso: 'LSL' },
    { name: 'Liberian Dollar', symbol: 'LRD', iso: 'LRD' },
    { name: 'Libyan Dinar', symbol: 'LYD', iso: 'LYD' },
    { name: 'Malagasy Ariary', symbol: 'MGA', iso: 'MGA' },
    { name: 'Malawian Kwacha', symbol: 'MWK', iso: 'MWK' },
    { name: 'Malaysian Ringgit', symbol: 'MYR', iso: 'MYR' },
    { name: 'Maldivian Rufiyaa', symbol: 'MVR', iso: 'MVR' },
    { name: 'Maltese Lira (pre-Euro)', symbol: 'MTL', iso: 'MTL' },
    { name: 'Mauritian Rupee', symbol: 'MUR', iso: 'MUR' },
    { name: 'Mexican Peso', symbol: 'MXN', iso: 'MXN' },
    { name: 'Moldovan Leu', symbol: 'MDL', iso: 'MDL' },
    { name: 'Mongolian Tögrög', symbol: 'MNT', iso: 'MNT' },
    { name: 'Moroccan Dirham', symbol: 'MAD', iso: 'MAD' },
    { name: 'Mozambican Metical', symbol: 'MZN', iso: 'MZN' },
    { name: 'Myanmar Kyat', symbol: 'MMK', iso: 'MMK' },
    { name: 'Namibian Dollar', symbol: 'NAD', iso: 'NAD' },
    { name: 'Nepalese Rupee', symbol: 'NPR', iso: 'NPR' },
    { name: 'Netherlands Antillean Guilder', symbol: 'ANG', iso: 'ANG' },
    { name: 'New Zealand Dollar', symbol: 'NZD', iso: 'NZD' },
    { name: 'Nigerian Naira', symbol: 'NGN', iso: 'NGN' },
    { name: 'North Korean Won', symbol: 'KPW', iso: 'KPW' },
    { name: 'Norwegian Krone', symbol: 'NOK', iso: 'NOK' },
    { name: 'Omani Rial', symbol: 'OMR', iso: 'OMR' },
    { name: 'Pakistani Rupee', symbol: 'PKR', iso: 'PKR' },
    { name: 'Papua New Guinean Kina', symbol: 'PGK', iso: 'PGK' },
    { name: 'Paraguayan Guarani', symbol: 'PYG', iso: 'PYG' },
    { name: 'Peruvian Sol', symbol: 'PEN', iso: 'PEN' },
    { name: 'Philippine Peso', symbol: 'PHP', iso: 'PHP' },
    { name: 'Polish Zloty', symbol: 'PLN', iso: 'PLN' },
    { name: 'Portuguese Escudo (pre-Euro)', symbol: 'PTE', iso: 'PTE' },
    { name: 'Qatari Rial', symbol: 'QAR', iso: 'QAR' },
    { name: 'Romanian Leu', symbol: 'RON', iso: 'RON' },
    { name: 'Russian Ruble', symbol: 'RUB', iso: 'RUB' },
    { name: 'Rwandan Franc', symbol: 'RWF', iso: 'RWF' },
    { name: 'Saint Helena Pound', symbol: 'SHP', iso: 'SHP' },
    { name: 'Samoan Tala', symbol: 'WST', iso: 'WST' },
    { name: 'Sao Tome and Principe Dobra', symbol: 'STN', iso: 'STN' },
    { name: 'Saudi Riyal', symbol: 'SAR', iso: 'SAR' },
    { name: 'Serbian Dinar', symbol: 'RSD', iso: 'RSD' },
    { name: 'Seychellois Rupee', symbol: 'SCR', iso: 'SCR' },
    { name: 'Singapore Dollar', symbol: 'SGD', iso: 'SGD' },
    { name: 'Slovak Koruna', symbol: 'SKK', iso: 'SKK' },
    { name: 'Slovenian Tolar (pre-Euro)', symbol: 'SIT', iso: 'SIT' },
    { name: 'Solomon Islands Dollar', symbol: 'AUD', iso: 'AUD' },
    { name: 'Somali Shilling', symbol: 'SOS', iso: 'SOS' },
    { name: 'South African Rand', symbol: 'ZAR', iso: 'ZAR' },
    { name: 'South Korean Won', symbol: 'KRW', iso: 'KRW' },
    { name: 'Spanish Peseta (pre-Euro)', symbol: 'ESP', iso: 'ESP' },
    { name: 'Sri Lankan Rupee', symbol: 'LKR', iso: 'LKR' },
    { name: 'Sudanese Pound', symbol: 'SDG', iso: 'SDG' },
    { name: 'Surinamese Dollar', symbol: 'SRD', iso: 'SRD' },
    { name: 'Swedish Krona', symbol: 'SEK', iso: 'SEK' },
    { name: 'Swiss Franc', symbol: 'CHF', iso: 'CHF' },
    { name: 'Syrian Pound', symbol: 'SYP', iso: 'SYP' },
    { name: 'Taiwan Dollar', symbol: 'TWD', iso: 'TWD' },
    { name: 'Tajikistani Somoni', symbol: 'TJS', iso: 'TJS' },
    { name: 'Tanzanian Shilling', symbol: 'TZS', iso: 'TZS' },
    { name: 'Thai Baht', symbol: 'THB', iso: 'THB' },
    { name: 'Tunisian Dinar', symbol: 'TND', iso: 'TND' },
    { name: 'Turkish Lira', symbol: 'TRY', iso: 'TRY' },
    { name: 'Turkmenistani Manat', symbol: 'TMT', iso: 'TMT' },
    { name: 'Tuvaluan Dollar', symbol: 'AUD', iso: 'AUD' },
    { name: 'Ugandan Shilling', symbol: 'UGX', iso: 'UGX' },
    { name: 'Ukrainian Hryvnia', symbol: 'UAH', iso: 'UAH' },
    { name: 'United Arab Emirates Dirham', symbol: 'AED', iso: 'AED' },
    { name: 'United States Dollar', symbol: 'USD', iso: 'USD' },
    { name: 'Uruguayan Peso', symbol: 'UYU', iso: 'UYU' },
    { name: 'Uzbekistani Som', symbol: 'UZS', iso: 'UZS' },
    { name: 'Vanuatu Vatu', symbol: 'VUV', iso: 'VUV' },
    { name: 'Venezuelan Bolívar', symbol: 'VES', iso: 'VES' },
    { name: 'Vietnamese Dong', symbol: 'VND', iso: 'VND' },
    { name: 'Yemeni Rial', symbol: 'YER', iso: 'YER' },
    { name: 'Zambian Kwacha', symbol: 'ZMW', iso: 'ZMW' },
    { name: 'Zimbabwean Dollar', symbol: 'ZWL', iso: 'ZWL' },
];