version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: bill-tracker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-initdb.d:/docker-entrypoint-initdb.d
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: '${MYSQL_USER}'
      PMA_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: always

networks:
  default:
    name: bill-tracker-network

volumes:
  mysql_data:
