version: "3.8"

services:
  api:
    image: node:18
    container_name: bill-tracker-api
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - TYPEORM_DATABASE_HOST: ${MYSQL_HOST}
      - TYPEORM_DATABASE_PORT: 3306
      - TYPEORM_DATABASE_USERNAME: ${MYSQL_USER}
      - TYPEORM_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      - TYPEORM_DATABASE_NAME: ${MYSQL_DATABASE}
      - JWT_KEY: FBBA8FCCCD175E685BAD1F661E3D8
      - THROTTLE_TTL: 5000
      - THROTTLE_LIMIT: 2
    command: sh -c "npm install && npm run start"

networks:
  default:
    name: bill-tracker-network

volumes:
  mysql_data:
