version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: bill_tracker
    volumes:
      - mysql_data:/var/lib/mysql

  bill-tracker-api:
    build:
      context: ./
    container_name: bill-tracker-api
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: admin
      DB_NAME: bill_tracker
    command: >
      sh -c "
      npm install &&
      npm run migrate &&
      npm run start
      "

  backup:
    image: alpine
    container_name: backup
    depends_on:
      - mysql
    volumes:
      - ./backup:/backup
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "while true; do
      /bin/sh /backup/backup.sh;
      sleep 86400;
      done"

volumes:
  mysql_data:
