jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Use a specific version

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy API to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@88.222.245.88 << 'EOF'
            set -e  # Exit immediately if a command exits with a non-zero status
            if [ ! -d "/bill-tracker/.git" ]; then
              git clone https://github.com/Kim-Avillanosa/bill-tracker.git /bill-tracker  # Replace with your repo URL
            else
              cd /bill-tracker
              git stash || true  # Stash local changes if any
              git pull origin main
              git stash pop || true  # Apply the stashed changes back if any
            fi

            # Deploy API
            cd /bill-tracker/api
            docker-compose down bill-tracker-api || true  # Ignore errors from down
            docker-compose up bill-tracker-api -d --build
          EOF
