name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no root@88.222.245.88 'echo "SSH connection successful!"'

      - name: Deploy API to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@88.222.245.88 << 'EOF'
            # Check if the directory exists; if not, create it
            [ ! -d /bill-tracker/api ] && mkdir -p /bill-tracker/api
            
            cd /bill-tracker/api || { echo "Failed to change directory"; exit 1; }
            git pull origin main || { echo "Git pull failed"; exit 1; }
            docker-compose down || { echo "Docker-compose down failed"; exit 1; }
            docker-compose up -d --build || { echo "Docker-compose up failed"; exit 1; }
          EOF

      - name: Deploy App to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@88.222.245.88 << 'EOF'
            # Check if the directory exists; if not, create it
            [ ! -d /bill-tracker/app ] && mkdir -p /bill-tracker/app
            
            cd /bill-tracker/app || { echo "Failed to change directory"; exit 1; }
            git pull origin main || { echo "Git pull failed"; exit 1; }
            docker-compose down || { echo "Docker-compose down failed"; exit 1; }
            docker-compose up -d --build || { echo "Docker-compose up failed"; exit 1; }
          EOF
