name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no root@88.222.245.88 'echo "SSH connection successful!"'

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@88.222.245.88 << 'EOF'
            # Define directories
            API_DIR=/bill-tracker/api
            APP_DIR=/bill-tracker/app

            # Clone or pull the API repository
            if [ ! -d $API_DIR/.git ]; then
              git clone https://github.com/Kim-Avillanosa/bill-tracker.git $API_DIR  # Replace with actual repository URL
            else
              cd $API_DIR
              git pull origin main || { echo "Git pull failed"; exit 1; }
            fi
            
            # Bring down the services without affecting MySQL
            cd $API_DIR
            docker-compose down || { echo "Docker-compose down failed"; exit 1; }
            docker-compose up -d --build || { echo "Docker-compose up failed"; exit 1; }

            # Clone or pull the App repository
            if [ ! -d $APP_DIR/.git ]; then
              git clone https://github.com/Kim-Avillanosa/bill-tracker.git $APP_DIR  # Replace with actual repository URL
            else
              cd $APP_DIR
              git pull origin main || { echo "Git pull failed"; exit 1; }
            fi
            
            # Bring down the services without affecting MySQL
            cd $APP_DIR
            docker-compose down || { echo "Docker-compose down failed"; exit 1; }
            docker-compose up -d --build || { echo "Docker-compose up failed"; exit 1; }
          EOF
